인턴십 2주차 후기
8percent/8percent.github.io pull request #48
Opened 2020-12-31 09:04 UTC by Lijuet

아직 미완성이에요.
오늘이나 내일 쯤 글 좀 더 다듬고 꾸밀 예정이에요

인턴기 올릴려니 부끄럽습니다🤦‍♀️🤦‍♀️🤦‍♀️

2021-01-02 00:03 UTC, leehosung commented
작업 완료 되시면 리뷰어에 저를 추가해 주세요~

2021-01-04 01:10 UTC, leehosung commented on _posts/2020-12-31-internship-review.md
> +![eifhrPercenr](file:///Users/8percent/Downloads/IMG_0148.JPG)
이미지 패스를 다른 글을 참고해서 수정해 주셔야 할것 같네요. 이미지도 함께 업로드 되어야 합니다.

2021-01-04 01:11 UTC, leehosung commented on _posts/2020-12-31-internship-review.md
> +<span style="color:#6741d9">인턴 동안 진행할 프로젝트는 휴머스온으로 운영된 SMS, 알림톡 서비스를 N 클라우드 금융 플랫폼으로 옮기고 이에 관한 기록을 DB에 남기는 작업이다. </span>이 프로젝트를 시작하기 위해서는 8퍼센트 이해와 장고 학습이 필요하므로, 다른 쉬운 일을 몇 가지 맡으며 공부하고 시작하기로 했다.
```suggestion
<span style="color:#6741d9">인턴 동안 진행할 프로젝트는 휴머스온으로 운영된 SMS, 알림톡 서비스를 N 클라우드 금융 플랫폼으로 옮기고 이에 관한 기록을 DB에 남기는 작업이다. </span>이 프로젝트를 시작하기 위해서는 8퍼센트 서비스 구조에 대한 이해와  Django 학습이 필요하므로, 다른 쉬운 일을 몇 가지 맡으며 공부하고 시작하기로 했다.
```

2021-01-04 01:12 UTC, leehosung commented on _posts/2020-12-31-internship-review.md
> +<span style="color:#6741d9">인턴 동안 진행할 프로젝트는 휴머스온으로 운영된 SMS, 알림톡 서비스를 N 클라우드 금융 플랫폼으로 옮기고 이에 관한 기록을 DB에 남기는 작업이다. </span>이 프로젝트를 시작하기 위해서는 8퍼센트 이해와 장고 학습이 필요하므로, 다른 쉬운 일을 몇 가지 맡으며 공부하고 시작하기로 했다.
보통 장고 라고 한글로는 잘 쓰지 않는것 같아요. 동일한 단어가 있기 때문인것 같아요.

2021-01-04 01:12 UTC, leehosung commented on _posts/2020-12-31-internship-review.md
> +2주 동안 약 **5가지의 request**를 받아서 했다. 코드 수정 자체는 많지 않고 쉬운 편인데, 장고가 처음이다 보니 프로젝트 구조가 익숙하지 않아 어떤 코드를 고쳐야 하는지가 헷갈렸다. requesr를 받으면 스스로 찾아보고 그래도 모르는 부분은 다른 팀원분들께 물어보면서 해결했다. 코드 수정하고 안전하게 돌아갈지 꼭 테스트를 해봐야 한다. 로컬
```suggestion
2주 동안 약 **5가지의 request**를 받아서 했다. 코드 수정 자체는 많지 않고 쉬운 편인데, 장고가 처음이다 보니 프로젝트 구조가 익숙하지 않아 어떤 코드를 고쳐야 하는지가 헷갈렸다. request를 받으면 스스로 찾아보고 그래도 모르는 부분은 다른 팀원분들께 물어보면서 해결했다. 코드 수정하고 안전하게 돌아갈지 꼭 테스트를 해봐야 한다. 로컬로 돌려보고 장고 테스트 코드를 작성해서 테스트해 본다. 그 후 PR을 올려 다른 팀원분들의 리뷰를 받는다. 리뷰를 반영하면 머지하고 배포한다. (배포할 때는 비록 내가 고친 부분은 발톱의 때 수준이긴 한데, 혹시 내 코드 때문에 문제가 생길까 봐 진짜 떨렸다)
```

2021-01-04 01:15 UTC, leehosung commented on _posts/2020-12-31-internship-review.md
> +실무는 학교에서 배운 거랑 전혀 다르며 규모도 커서 어렵다는 소리를 많이 들어서 긴장을 많이 했다. 거대한 프로젝트에 내가 잘못해서 문제가 생기면 어찌하나? 라는 생각돋 들었다. 맥과 장고도 처음이고, (내가 원해서 온거지만) 아직 이해할 수 없는 금융 용어가 파이썬인척하며 코드 사이에 들어있다. 유튜브 찾아보니 또 인턴 때 주의할 것이 너무 질문하는 것
```suggestion
실무는 학교에서 배운 거랑 전혀 다르며 규모도 커서 어렵다는 소리를 많이 들어서 긴장을 많이 했다. 거대한 프로젝트에 내가 잘못해서 문제가 생기면 어찌하나? 라는 생각도 들었다. 맥과 장고도 처음이고, (내가 원해서 온거지만) 아직 이해할 수 없는 금융 용어가 파이썬인척하며 코드 사이에 들어있다. 유튜브 찾아보니 또 인턴 때 주의할 것이 너무 질문하는 것도 안 좋아하고 그렇다고 너무 질문 안 하면 답답해한다는 조언을 많이 봤다. 과제를 받고 하면서 모르는 게 나왔을 때(대부분 모른다;) 구글, 프로젝트 소스 검색을 하다 모르겠다 싶으면 한 10번 고민하다가 물어봤다. 근데 물어보면 다들 정말 친절하게 설명해주신다. 심지어 막힌 거 없냐고 오셔서 물어봐주신다. 처음에는 이것도 죄송했는데, 내가 제대로 배우는 것이 더 중요하다는 생각에 이제는 좀 찾아보고 뭐가 궁금한 건지 정확히 정리해서 물어봤다. 그리고 원래 문서화하는 습관이 없었는데, 실수하거나 질문 횟수를 줄이기 위해서 Today-I-Learned와 주차 보고서를 쓰는 등 모르는 것을 문서화하는 습관을 들이기 시작했다.
```

2021-01-04 01:17 UTC, leehosung commented on _posts/2020-12-31-internship-review.md
> +돈과 관련된 개인정보가 담긴 DB를 가지고 일하는 만큼 보안이 정말 중요하다. 그래서 첫날부터 자리를 비울 때는 꼭 노트북을 잠그고 가라고 안 그러면 **털린다**고 주의를 주셨다. 털린다는 게 무슨 의미인지 잘 안 와닿았을 때, 잠깐 노트북을 잠그지 않은 채로 자리를 비운 적이 있었다. 아직 어색해서 한마디도 못 한 잡담 채널에서 내 첫 마디가 **'세
이런건 캡춰를 넣어주면 생동감이 있고 재미있습니다. :)

2021-01-04 01:18 UTC, leehosung commented on _posts/2020-12-31-internship-review.md
> +author: Chae Selee
author 정보를  _config.yml 파일에 등록해 주셔야 합니다. 살펴 보세요.

2021-01-04 01:18 UTC, leehosung commented on _posts/2020-12-31-internship-review.md
> +#<span style="color:#6741d9">8퍼센트</span>에 지원한 이유
마크다운 문법에 대해서 혹시 어떻게 체크를 하셨나요? 
# 뒤에 띄어쓰기가 없어도 문제가 없던가요?

2021-01-04 01:19 UTC, leehosung requested changes
리뷰 했습니다. 

공식적으로 올리는 글들을 맞춤법 검사기를 한번씩 돌리는 것이 좋습니다.

2021-01-04 02:39 UTC, Lijuet commented
> 리뷰 했습니다.
> 
> 공식적으로 올리는 글들을 맞춤법 검사기를 한번씩 돌리는 것이 좋습니다.

꼼꼼한 리뷰 감사합니다. 수정했습니다!

2021-01-04 05:49 UTC, leehosung approved these changes
확인했습니다. publish! 해보시죠.

2021-01-04 06:15 UTC, merged